--- #This is an Ansible script to change the user password from all Windows machines
- hosts: '{{ hosts }}'
  gather_facts: yes
  vars_prompt:
    hosts: "Please enter the hosts list that you wish to run this script"
  tasks:
    - include: tasks_disable_proxy.yaml  
...
