- name: Disabling Firewall before package installation
  action: win_shell REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f 

- name: Disabling auto detection of proxy/network settings
  action: win_shell REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v AutoDetect /t REG_DWORD /d 0 /f
  
- name: Disabling protected mode internet explorer settings
  action: win_shell REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 2500 /t REG_DWORD /d 3 /f  
  
- name: Enabling download of files in internet explorer settings
  action: win_shell REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 1803 /t REG_DWORD /d 0 /f

